plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = 'android.llama.cpp'
    compileSdk =35
    ndkVersion= "28.0.13004108"
    defaultConfig {
        minSdk = libs.versions.minSdkVersion.get().toInteger()
        targetSdk =libs.versions.targetSdkVersion.get().toInteger()

        testInstrumentationRunner= "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        ndk {
            // Add NDK properties if wanted, e.g.
            //abiFilters "arm64-v8a","x86_64"
            //abiFilters "x86_64"
//            abiFilters += [ "x86", "x86_64", "armeabi-v7a", "arm64-v8a", "riscv64" ]
            abiFilters +=["arm64-v8a"]
        }

        externalNativeBuild {
            cmake {
                arguments += "-DLLAMA_BUILD_COMMON=ON"
                arguments += "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
                arguments += "-DCMAKE_BUILD_TYPE=Release"
                cppFlags ''
            }
        }
    }
    packagingOptions {
        jniLibs {
            excludes += ['lib/arm64-v8a/libOpenCL.so']
        }
    }


    buildTypes {
        release {
            minifyEnabled  false
            proguardFiles  getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility =JavaVersion.VERSION_11
        targetCompatibility =JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        //prefab =true
        prefabPublishing =true
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version = '3.31.5'
        }
    }



    prefab {
        "llama" {
            headers = "src/main/cpp/llama.cpp/include"
        }
        "ggml-cpu" {
            //headers "src/main/cpp/llama.cpp/ggml/src/ggml-cpu"
        }

        "ggml-base" {
            //headers "src/main/cpp/llama.cpp/ggml/src"
        }

        "ggml" {
            headers = "src/main/cpp/llama.cpp/ggml/include"
        }


    }
}

dependencies {

    //implementation libs.androidx.core.ktx
    implementation(libs.androidx.annotation)
    implementation(libs.kotlinx.coroutines.android)
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}